{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shadowtext
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shadowtext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shadowtext/shadowtext_{{ version }}.tar.gz
  sha256: d4485d18c8975e03de22b8627f0436928b905a947f272dab958c2f79127b032c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-scales
  run:
    - r-base
    - r-ggplot2
    - r-scales

test:
  commands:
    - $R -e "library('shadowtext')"           # [not win]
    - "\"%R%\" -e \"library('shadowtext')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/shadowtext/
  license: Artistic-2.0
  summary: Implement shadowtextGrob() for 'grid' and geom_shadowtext() layer for 'ggplot2'. These functions create/draw text grob with background shadow.
  license_family: OTHER
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shadowtext
# Title: Shadow Text Grob and Layer
# Version: 0.0.6
# Authors@R: person("Guangchuang", "Yu", email = "guangchuangyu@gmail.com", role = c("aut", "cre"))
# Description: Implement shadowtextGrob() for 'grid' and geom_shadowtext() layer for 'ggplot2'. These functions create/draw text grob with background shadow.
# Depends: R (>= 3.4.0)
# Imports: ggplot2, grid, scales
# Suggests: knitr, prettydoc
# VignetteBuilder: knitr
# License: Artistic-2.0
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/GuangchuangYu/shadowtext/
# BugReports: https://github.com/GuangchuangYu/shadowtext/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-09 04:50:19 UTC; ygc
# Author: Guangchuang Yu [aut, cre]
# Maintainer: Guangchuang Yu <guangchuangyu@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-09 05:10:02 UTC
